// 仅复用临时数据库与合成音源；安全探测应拒绝 fixture 的 localhost 上游。
const assert = require('node:assert/strict')
const path = require('node:path')
module.exports = async function ({ check, url, artifacts, login }) {
  await check('限时调试普通用户不可见且后台拒绝', async page => {
    assert.equal(await page.locator('nav [data-tab=debug]').isVisible(), false)
    assert.equal((await page.request.get(url + '/api/admin/debug-tokens')).status(), 403)
    assert.equal((await page.request.post(url + '/api/admin/debug-tokens', { data: {}, headers: { Origin: url, 'X-LXSC-Debug-Management': '1' } })).status(), 403)
    assert.equal((await page.request.get(url + '/api/debug/status')).status(), 401)
    await page.evaluate(() => { location.hash = '#debug' })
    await page.waitForFunction(() => location.hash === '#playlists')
  })
  await check('限时调试创建、分享复制降级、权限、撤销与离开清理', async page => {
    await page.locator('#logoutButton').click()
    await page.locator('#login:not(.hidden)').waitFor()
    await login(page, url, 'admin')
    await page.locator('nav [data-tab=debug]').click()
    await page.locator('#tab-debug.active').waitFor()
    assert.equal(await page.locator('#debugHTTPSWarning').isVisible(), true)
    assert.equal(await page.locator('#debugTTL').inputValue(), '900')
    assert.equal(await page.locator('#debugPreset').inputValue(), 'full')
    await page.locator('#debugPreset').selectOption('read')
    const creation = page.waitForResponse(response => response.url() === url + '/api/admin/debug-tokens' && response.request().method() === 'POST')
    await page.locator('#debugCreateButton').click()
    const response = await creation
    assert.equal(response.status(), 201)
    assert.equal(response.headers()['cache-control'], 'no-store')
    assert.equal(response.request().headers()['x-lxsc-debug-management'], '1')
    const data = await response.json(), token = data.token
    await page.locator('#debugSecret:not(.hidden)').waitFor()
    assert.equal(await page.locator('#debugTokenValue').inputValue(), token)
    assert.ok(!(await page.locator('#debugTokenList').innerText()).includes(token))
    const headers = { Authorization: 'Bearer ' + token }
    assert.equal((await page.request.get(url + '/api/debug/status', { headers })).status(), 200)
    assert.equal((await page.request.get(url + '/api/debug/events', { headers })).status(), 200)
    const capabilities = await (await page.request.get(url + '/api/debug/capabilities', { headers })).json()
    assert.equal(capabilities.diagnosticsVersion, 3)
    assert.equal(capabilities.administratorOnly, true)
    assert.equal(capabilities.clientLogin, false)
    assert.equal((await page.request.post(url + '/api/debug/probe', { headers, data: { trackId: 'tr-wy-1', quality: '320k' } })).status(), 403)
    await page.evaluate(() => {
      window.debugCopied = []
      Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async value => window.debugCopied.push(value) } })
    })
    await page.locator('#debugCopyShare').click()
    const copied = await page.evaluate(() => window.debugCopied[0])
    for (const part of [url, 'Bearer ' + token, data.credential.expiresAt, '/api/debug/status', '/api/debug/capabilities', 'read']) assert.ok(copied.includes(part))
    await page.evaluate(() => { navigator.clipboard.writeText = async () => { throw new Error('无剪贴板权限') } })
    await page.locator('#debugCopyToken').click()
    assert.equal(await page.locator('#debugTokenValue').evaluate(el => document.activeElement === el && el.selectionStart === 0 && el.selectionEnd === el.value.length), true)
    await page.locator(`[data-debug-revoke="${data.credential.id}"]`).click()
    await page.waitForFunction(() => document.querySelector('#debugTokenValue').value === '')
    assert.equal((await page.request.get(url + '/api/debug/status', { headers })).status(), 401)
    await page.locator('#debugPreset').selectOption('full')
    await page.locator('#debugTTL').selectOption('3600')
    const activeCreate = page.waitForResponse(response => response.url() === url + '/api/admin/debug-tokens' && response.request().method() === 'POST')
    await page.locator('#debugCreateButton').click()
    const active = await (await activeCreate).json()
    const activeHeaders = { Authorization: 'Bearer ' + active.token }
    assert.deepEqual(active.credential.scopes, ['read', 'probe', 'inspect', 'maintain'])
    for (const kind of ['runtime', 'performance', 'settings', 'sources', 'logs']) {
      assert.equal((await page.request.get(url + '/api/debug/inspect/' + kind, { headers: activeHeaders })).status(), 200)
    }
    const protocol = await page.request.post(url + '/api/debug/probe/protocol', { headers: activeHeaders, data: { endpoint: 'getLyricsBySongId', method: 'GET', format: 'json', params: { id: 'tr-wy-1' } } })
    assert.equal(protocol.status(), 200)
    const protocolResult = await protocol.json()
    assert.equal(protocolResult.result.protocolStatus, 'ok')
    assert.ok(protocolResult.result.lines > 0)
    assert.equal(protocolResult.playbackPersisted, false)
    const playback = await page.request.post(url + '/api/debug/probe/playback', { headers: activeHeaders, data: { trackId: 'tr-wy-1', method: 'HEAD', quality: '320k' } })
    assert.equal(playback.status(), 200)
    const playbackResult = await playback.json()
    assert.ok([200, 302].includes(playbackResult.result.status))
    assert.equal(playbackResult.playbackPersisted, false)
    const maintenance = await page.request.post(url + '/api/debug/maintenance', { headers: activeHeaders, data: { operation: 'cache_clear', target: 'urls' } })
    assert.equal(maintenance.status(), 200)
    assert.equal((await maintenance.json()).ok, true)
    for (const [kind, data, field] of [['board', { boardId: 'lb-wy-hot' }, 'count'], ['lyrics', { trackId: 'tr-wy-1' }, 'lines']]) {
      const response = await page.request.post(url + '/api/debug/probe/' + kind, { headers: activeHeaders, data })
      assert.equal(response.status(), 200)
      const body = await response.json()
      assert.equal(body.events[0].result, 'ok')
      assert.ok(body.events[0][field] > 0)
      assert.ok(!JSON.stringify(body).includes('测试歌词'))
    }
    await page.request.get(url + '/rest/getLyricsBySongId?u=alice&p=test-password&c=Amcfy&f=json&id=tr-wy-1')
    const observed = await (await page.request.get(url + '/api/debug/events', { headers: activeHeaders })).json()
    assert.ok(observed.events.some(event => event.stage === 'client_response' && event.client === 'amcfy' && event.endpoint === 'getLyricsBySongId' && event.lines > 0))
    const probe = await page.request.post(url + '/api/debug/probe', { headers: { Authorization: 'Bearer ' + active.token }, data: { trackId: 'tr-wy-1', quality: '320k' } })
    assert.equal(probe.status(), 200)
    const result = await probe.json()
    assert.equal(result.events.at(-1).error, 'blocked_target')
    assert.ok(!JSON.stringify(result).includes('127.0.0.1'))
    await page.locator('#debugSecret:not(.hidden)').waitFor()
    // 截图前主动清除一次性密钥，验收工件不保存凭据。
    await page.locator('#debugClear').click()
    await page.screenshot({ path: path.join(artifacts, 'debug-management.png'), fullPage: true })
    await page.locator('nav [data-tab=search]').click()
    assert.equal(await page.locator('#debugShareValue').inputValue(), '')
    await page.locator('nav [data-tab=debug]').click()
    assert.equal(await page.locator('#debugSecret').isVisible(), false)
    const storage = await page.evaluate(() => JSON.stringify([Object.entries(localStorage), Object.entries(sessionStorage), location.href]))
    assert.ok(!storage.includes(token) && !storage.includes(active.token))
    await page.locator(`[data-debug-revoke="${active.credential.id}"]`).click()
    await page.locator('#logoutButton').click()
    await page.locator('#login:not(.hidden)').waitFor()
    assert.equal(await page.locator('#debugTokenValue').inputValue(), '')
    assert.equal(await page.locator('#debugTokenList').innerText(), '')
  }, { viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
}
