const assert = require('node:assert/strict')
const path = require('node:path')
module.exports = async ({ check, url, login, search, playSearch, createPlaylist, selectPlaylistUI, artifacts }) => {
  await check('队列编辑、循环设置、恢复暂停与歌词跳转', async page => {
    await search(page, '队列验收'); await playSearch(page)
    await page.locator('#playerQueue').click()
    await page.locator('#playerRepeat').selectOption('all')
    await page.locator('#playerShuffle').click()
    await page.locator('[data-queue-action=down][data-index="0"]').click()
    assert.equal(await page.evaluate(() => webPlayer.track.id), 'tr-wy-1')
    assert.equal(await page.evaluate(() => webPlayer.index), 1)
    await page.screenshot({ path: path.join(artifacts, 'queue-desktop.png'), fullPage: true })
    await page.locator('#closeQueue').click()
    await page.locator('#playerToggle').click()
    await page.reload()
    await page.waitForFunction(() => sessionState.me && webPlayer.track)
    assert.equal(await page.evaluate(() => webPlayer.audio.paused), true)
    assert.equal(await page.evaluate(() => webPlayer.repeat), 'all')
    assert.equal(await page.evaluate(() => webPlayer.shuffle), true)
    assert.equal(await page.evaluate(() => webPlayer.index), 1)
    await page.route('**/api/app/lyrics?*', route => route.fulfill({ json: { lines: [{ start: 0, value: '第一行' }, { start: 10000, value: '第二行' }], trans: [{ start: 10000, value: '翻译' }], synced: true, offset: 0 } }))
    await page.locator('#playerToggle').click()
    await page.waitForFunction(() => webPlayer.duration > 0)
    await page.locator('#playerLyrics').click()
    await page.locator('[data-line="1"]').click()
    await page.waitForFunction(() => webPlayer.audio.currentTime >= 10)
    assert.match(await page.locator('[data-line="1"]').textContent(), /翻译/)
    await page.screenshot({ path: path.join(artifacts, 'lyrics-desktop.png'), fullPage: true })
    await page.locator('#closeLyrics').click()
    await page.locator('#logoutButton').click(); await page.locator('#login:not(.hidden)').waitFor()
    assert.equal(await page.evaluate(() => webPlayer.queue.length), 0)
    assert.equal(await page.evaluate(() => Object.keys(localStorage).filter(key => key.startsWith('lxsc.player.')).length), 0)
  })
  await check('搜索分页按平台请求且保留先前结果', async page => {
    await search(page, '分页')
    let requestedPage
    await page.route('**/api/app/search/stream', route => {
      requestedPage = route.request().postDataJSON().page
      const track = { id: 'tr-wy-page2', name: '第二页歌曲', singer: '歌手', source: 'wy' }
      return route.fulfill({ contentType: 'application/x-ndjson', body: [{ type: 'start', sources: ['wy'] }, { type: 'platform', source: 'wy', status: 'ok', tracks: [track] }, { type: 'done' }].map(JSON.stringify).join('\n') + '\n' })
    })
    await page.locator('[data-search-page=wy]').click()
    await page.waitForFunction(() => songSearchState.tracks.length === 4)
    assert.equal(requestedPage, 2)
    assert.equal(await page.locator('#searchTable tbody tr').count(), 4)
  })
  await check('订阅预览与追加更新、版本替换草稿', async page => {
    const p = await createPlaylist(page, url, '订阅验收')
    await selectPlaylistUI(page, p.id)
    await page.locator('#subscriptionOpen').click()
    await page.waitForFunction(() => document.querySelector('#subscriptionStatus').textContent !== '正在读取…')
    await page.locator('#subscriptionForm [name=input]').fill('12345')
    await page.locator('#subscriptionForm button').click()
    await page.waitForFunction(() => document.querySelector('#subscriptionStatus').textContent.includes('已保存'))
    await page.locator('#subscriptionPreview').click()
    await page.waitForFunction(() => !document.querySelector('#subscriptionApply').disabled)
    await page.locator('#subscriptionApply').click()
    await page.waitForFunction(() => document.querySelector('#subscriptionStatus').textContent.includes('更新完成'))
    await page.screenshot({ path: path.join(artifacts, 'subscription-desktop.png'), fullPage: true })
    await page.locator('#closeSubscription').click()
    assert.equal(await page.locator('#trackTable tr').count(), 3)
    await page.locator('[data-track-index="0"] [data-track-action=repair]').click()
    await page.locator('#repairForm button').click()
    await page.locator('[data-repair-use="0"]').click()
    assert.equal(await page.evaluate(() => playlistState.tracksDirty), true)
    assert.equal(await page.evaluate(() => playlistState.draftTracks.length), 3)
  })
  await check('API Key生成、列表与撤销', async page => {
    await page.locator('#logoutButton').click(); await page.locator('#login:not(.hidden)').waitFor(); await login(page, url, 'admin')
    await page.locator('nav [data-tab=users]').click()
    await page.locator('[data-user-action=key]').first().click()
    await page.locator('#keyCreateForm [name=label]').fill('验收设备')
    await page.locator('#keyCreateForm button').click()
    await page.waitForFunction(() => document.querySelector('#keyValue').value.startsWith('lxsc_'))
    const key = await page.locator('#keyValue').inputValue()
    const endpoint = url + '/rest/getUser?f=json&apiKey=' + encodeURIComponent(key)
    const before = await (await page.request.get(endpoint)).json()
    assert.equal(before['subsonic-response'].status, 'ok')
    page.once('dialog', dialog => dialog.accept())
    await page.locator('#keyList [data-revoke-key]').first().click()
    await page.waitForFunction(() => document.querySelectorAll('#keyList [data-revoke-key]').length === 0)
    const after = await (await page.request.get(endpoint)).json()
    assert.equal(after['subsonic-response'].status, 'failed')
    await page.locator('#closeAPIKey').click()
    assert.equal(await page.locator('#keyValue').inputValue(), '')
  })
}
